### ISSUE TITLE
Delete all remote lab code and issues

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop-apps#174]
PSLab remote has a dedicated repo. Therefore take out all code from this repo and close issues.

**Comment by jithinbp** [comment]
I already did this in a [commit](https://github.com/fossasia/pslab-desktop-apps/pull/173/commits/e855fb5589ed282fe4c042c1cf9535b370da6d9d) about an hour ago. I failed to create and reference an issue here, but I've created one in the new repository before moving it.
In the README.md of the new repository, I've also added links to the relevant PRs in this repository for the sake of continuity .
can this issue be closed and forgotten now?
