### ISSUE TITLE
Some of the dependencies aren't available on new systems

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-desktop-apps#201]
**Current behavior**

Dependencies like qtwebkit aren't available on new Linux system and so they obstructs the app to open

**Expected behavior**

There should be some alternate dependencies available

**Would you like to work on the issue ?**

Yes

**Comment by harsh-2711** [comment]
@CloudyPadmal  I made a new version of Experiments file with new dependencies and also modified the file which installs the dependencies while first installing the software. So how should I make PR to keep both of our changes and how can we provide user to switch between downloading the app with these two different Experiments file?

**Comment by CloudyPadmal** [comment]
Nice! By installing extra dependencies, will it cause any issues in the system? If not we can have a single file with all the dependencies.

**Comment by CloudyPadmal** [comment]
Does PyQt4 not have qtwebkit?

**Comment by harsh-2711** [comment]
@CloudyPadmal It wasn't available for me when I downloaded PyQt4. I tried to download it from it's source code but then also it wasn't detected. So, I used qtwebkit from PySide

**Comment by harsh-2711** [comment]
@CloudyPadmal Should I proceed for a PR by making a new Experiments file? Then you can combine both as per the need in the main software.

**Comment by CloudyPadmal** [comment]
@harsh-2711 Yes please. Let's have a look at it and see!

**Comment by harsh-2711** [comment]
@CloudyPadmal I made the experiments file but while modifying dependencies, I found that we need to create a virtual environment to download PySide as given in its documentation. So we need user's interaction. And also Qt dependency is needed to download PySide. So should I proceed with these dependencies?

**Comment by CloudyPadmal** [comment]
I'm a little confused about what's causing this much of a mess when installing the desktop app. My PC is also 16.04 LTS. Can you just post the dependency files you've been creating? Are you certain that your PC had PyQt4, not PyQt5? Did you run the installer.sh script or manually installed? I thought the version you were trying is 18.04.

**Comment by harsh-2711** [comment]
@CloudyPadmal You can close this issue now as when I installed the application again it worked. I don't know what was the problem before. It might be I have been using a different version then.
