### ISSUE TITLE
Add all relevant information in /docs folder

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-desktop-apps#88]
The blog is a good place to get people attracted. Documentation itself should be kept in a /docs folder in the repository. So people are able to update it.

**Comment by anu0012** [comment]
@mariobehling Can I take this issue?

**Comment by mariobehling** [comment]
@anu0012 Sure, please take it up. Please consider that this is not just a simple copy/paste issue, but docs should be updated to reflect the latest developments. We can go step by step as well.

**Comment by anu0012** [comment]
@mariobehling Can you please tell me what kind of docs we can have?

**Comment by mariobehling** [comment]
Please move the info from these posts into the documentation here:

### Blog posts related to PSLab on FOSSASIA blog 
* [Installation of PSLab](http://blog.fossasia.org/pslab-code-repository-and-installation/)
* [Communicating with PSLab](http://blog.fossasia.org/communicating-with-pocket-science-lab-via-usb-and-capturing-and-plotting-sine-waves/)
* [New Tools and Sensors for Fossasia PSLab and ExpEYES](http://blog.fossasia.org/new-tools-and-sensors-fossasia-pslab-and-expeyes/)
